# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5857d5277c04df444e57a7c2c3c02568"
name = "spintura-spinswipe"
handle = "spintura-spinswipe"
application_url = "https://booty-hash-murray-when.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://booty-hash-murray-when.trycloudflare.com/auth/callback",
  "https://booty-hash-murray-when.trycloudflare.com/auth/shopify/callback",
  "https://booty-hash-murray-when.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
